// File generated by Antigravity (mocking flutterfire configure)
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxBAXEIOcVvE-nR90XutTNyFKV4zwOSG0',
    appId: '1:726229949996:web:5cc51bef3a6a726371bb89',
    messagingSenderId: '726229949996',
    projectId: 'bhidbhanjan-sakariya',
    authDomain: 'bhidbhanjan-sakariya.firebaseapp.com',
    storageBucket: 'bhidbhanjan-sakariya.firebasestorage.app',
    measurementId: 'G-RCXTQ78DVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBg2O6Wq6sd4eSpS2nQE7k673Lm9t_wI0',
    appId: '1:726229949996:android:af976567ca8aff2a71bb89',
    messagingSenderId: '726229949996',
    projectId: 'bhidbhanjan-sakariya',
    storageBucket: 'bhidbhanjan-sakariya.firebasestorage.app',
  );
}
